/*******************************************************************************
* BanSave_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class BanSave_TA extends SaveObject_TA;

var /*0x00080000-0x00000000*/ bool bViewedLastChanceModal;
