/*******************************************************************************
* ChallengeDropGroup_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class ChallengeDropGroup_TA extends CompleteTaskDropGroup_TA;

var databinding bool bPremium;

defaultproperties
{
	GFxDataClass=class'GFxData_ChallengeDropGroup_TA'
}