/*******************************************************************************
* ChallengeFilter_Default_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class ChallengeFilter_Default_TA extends ChallengeFilter_TA within ChallengeFolder_TA;
