/*******************************************************************************
* ContentSave_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class ContentSave_TA extends JsonSaveObject_TA;

var transient ContentConfig_TA Config;
var array<ContentPair> ContentMap2;
