/*******************************************************************************
* DynamicMapEventsConfig_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class DynamicMapEventsConfig_TA extends OnlineConfig_X;

var() /*0x00010000-0x00000000*/ bool bEnabled;
var() /*0x00010000-0x00000000*/ transient array<string> ActiveDynamicMapEvents;
