/*******************************************************************************
* GameSettingCategory_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class GameSettingCategory_TA extends GameSettingCategory_X;

var() MapSet_TA AllowedMapSet;
