/*******************************************************************************
* GFxData_ProductsSave_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class GFxData_ProductsSave_TA extends GFxDataSingleton_X;

defaultproperties
{
	TableName=ProductsSave
	ProxyClass=class'ProductsSave_TA'
}