/*******************************************************************************
* GFxData_EOSVoiceManager_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class GFxData_EOSVoiceManager_TA extends GFxDataSingleton_X;

var /*0x00010000-0x00000000*/ array<GFxData_EOSVoiceRoom_TA> TrackedRooms;
var /*0x00010000-0x00000000*/ transient EOSVoiceSettingsSave_TA VoiceSettingsSave;
var /*0x00010000-0x00000000*/ transient SoundSettingsSave_TA SoundSettingsSave;
var /*0x00010000-0x00000000*/ transient UISavedValues_TA UISavedValues;
var /*0x00010000-0x00000000*/ bool bPushToTalkActive;
var /*0x00010000-0x00000000*/ bool bInMapTransition;
var /*0x00010000-0x00000000*/ databinding bool bMainMenuNotifications;
var /*0x00010000-0x00000000*/ databinding bool bMatchNotifications;
var /*0x00010000-0x00000000*/ databinding bool bVoiceSettingEnabled;
var /*0x00010000-0x00000000*/ databinding bool bDisplayVoiceTab;
var /*0x00010000-0x00000000*/ databinding bool bVoiceFeatureEnabled;
var /*0x00010000-0x00000000*/ const float InactivePTTVolume;
var /*0x00010000-0x00000000*/ const float ActivePTTVolume;
var /*0x00010000-0x00000000*/ transient GameViewportClient_X ViewportClient;
var /*0x00018000-0x00000000*/ EOSVoiceManager_TA VoiceManager;
var /*0x00018000-0x00000000*/ EOSVoiceConfig_TA VoiceConfig;

defaultproperties
{
	ActivePTTVolume=50.0
	TableName=EOSVoice
	bLevelTransitionPersistent=true
}