/*******************************************************************************
* GFxData_MenuTreeNode_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class GFxData_MenuTreeNode_TA extends GFxDataRow_X;

defaultproperties
{
	PrimaryKeyName=NodeID
}