/*******************************************************************************
* GFxData_ChallengePage_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class GFxData_ChallengePage_TA extends GFxData_ChallengeFolder_TA;

var class ChallengeFilter;

defaultproperties
{
	
	TableName=ChallengePage
}