/*******************************************************************************
* GFxData_EOSVoiceManager_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class GFxData_EOSVoiceManager_TA extends GFxDataSingleton_X;

var array<GFxData_EOSVoiceRoom_TA> TrackedRooms;
var transient EOSVoiceSettingsSave_TA VoiceSettingsSave;
var transient SoundSettingsSave_TA SoundSettingsSave;
var transient UISavedValues_TA UISavedValues;
var bool bPushToTalkActive;
var bool bInMapTransition;
var databinding bool bMainMenuNotifications;
var databinding bool bMatchNotifications;
var databinding bool bVoiceSettingEnabled;
var databinding bool bDisplayVoiceTab;
var databinding bool bVoiceFeatureEnabled;
var const float InactivePTTVolume;
var const float ActivePTTVolume;
var transient GameViewportClient_X ViewportClient;
var EOSVoiceManager_TA VoiceManager;
var EOSVoiceConfig_TA VoiceConfig;

defaultproperties
{
	ActivePTTVolume=50.0
	TableName=EOSVoice
	bLevelTransitionPersistent=true
}