/*******************************************************************************
* GFxData_ESportConfig_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class GFxData_ESportConfig_TA extends GFxDataSingleton_X;

var ESportConfig_TA ESportEvents;

defaultproperties
{
	TableName=ESportEvents
	
}