/*******************************************************************************
* GFxModal_Tutorial_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class GFxModal_Tutorial_TA extends GFxModal_X;
