/*******************************************************************************
* JsonSaveObject_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class JsonSaveObject_TA extends SaveObject_TA;

var transient int CategoryPriority;
