/*******************************************************************************
* MatchBroadcastComponent_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class MatchBroadcastComponent_TA extends Component;

var MatchBroadcastLog_TA MatchLog;
var OnlineGame_Base_X OnlineGame;
