/*******************************************************************************
* MenuTreeNodeCrumbTrail_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class MenuTreeNodeCrumbTrail_TA extends Object within MenuTreeNode_TA;

var transient bool bTrailEnabled;
