/*******************************************************************************
* Mutator_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class Mutator_TA extends Object
	abstract;

var bool bRecordMetrics;

defaultproperties
{
	bRecordMetrics=true
}