/*******************************************************************************
* PersonaClubData generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class PersonaClubData extends Object;

var Persona_TA Persona;
var string ClubTagWithName;
var Qword ClubID;
