/*******************************************************************************
* ProductThumbnailAsset_Blueprint_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class ProductThumbnailAsset_Blueprint_TA extends ProductThumbnailAsset_TA;

var(Thumbnail) /*0x00030000-0x00000000*/ duplicatetransient const Texture2D RevealedThumbnail;
