/*******************************************************************************
* ProductLoader_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class ProductLoader_TA extends Component;

var array<Product_TA> RemainingProducts;
var array<ProductAsset_TA> Assets;
