/*******************************************************************************
* SampleRecordSettings_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class SampleRecordSettings_TA extends Component;

var() float MaxSampleAge;
var() float RecordRate;

defaultproperties
{
	MaxSampleAge=10.0
	RecordRate=60.0
}