/*******************************************************************************
* TargetFindConfig_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class TargetFindConfig_TA extends OnlineConfig_X;

var Qword StartTime;
var Qword EndTime;
var array<int> AffectedPlaylists;
