/*******************************************************************************
* TriggerClump_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class TriggerClump_TA extends Object;

var array<StatusTrigger_X> Triggers;
