/*******************************************************************************
* TutorialSave_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class TutorialSave_TA extends SaveObject_TA;

var array<string> TrainingEventsPlayed;
var array<string> TrainingEventsPerfected;
var array<int> DetailsGroupsSeen;
