/*******************************************************************************
* ViralItemFXComponent_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class ViralItemFXComponent_TA extends ActorComponent_X within Car_TA;

struct ViralFXData
{
	var() FXActor_TA FXArchetype;
	var() float Brightness;
	var() float GoldTint;
	var() AkSoundCue SFX;

	structdefaultproperties
	{
		FXArchetype=None
		Brightness=0.0
		GoldTint=0.0
		SFX=None
	}
};

var() array<ViralFXData> AuraFXDataList;
var() array<ViralFXData> TransmissionFXDataList;
var() array<name> AuraFXGameStateVisibility;
var transient FXActor_TA InfectedAuraFX;
var transient FXActor_TA TransmissionFX;
var transient AkSoundCue CurrentAuraSFX;
var transient EInfectedType InfectedStatus;
var transient PRI_TA CachedPRI;
var transient GameEvent_TA CachedGameEvent;
var const name AuraBrightnessParamName;
var const name GoldTintParamName;

defaultproperties
{
	AuraFXGameStateVisibility(0)=Countdown
	AuraFXGameStateVisibility(1)=WaitingForPlayers
	AuraFXGameStateVisibility(2)=PostGoalScored
}