/*******************************************************************************
* StringMap generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class StringMap extends Component
	native;

var native const Map_Mirror Map;
