blank_issues_enabled: true
contact_links:
  - name: Discord forum post
    url: https://discord.com/channels/711882968200904715/1075042356765659137
    about: Chat about this project in the RLMM Discord server