/*******************************************************************************
* AddReservationMessagePrivate_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class AddReservationMessagePrivate_X extends AddReservationMessage_X within ReservationBeacon_X
	config(Game);

var CustomMatchSettings Settings;
