/*******************************************************************************
* FXAttachmentTraitBase_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class FXAttachmentTraitBase_X extends Object within FXActor_X
	abstract
	editinlinenew
	collapsecategories
	hidecategories(Object);
