/*******************************************************************************
* LinkedAccountMap_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class LinkedAccountMap_X extends Component
	native;

var native Map_Mirror PlayerMap;
