/*******************************************************************************
* LocalPlayer_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class LocalPlayer_X extends LocalPlayer within Engine
	transient
	config(Engine);

var transient OnlinePlayer_X OnlinePlayer;
var transient ICabinedOrGuest CabinedOrGuest;
