/*******************************************************************************
* PartyConfig_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class PartyConfig_X extends OnlineConfig_X
	config(Engine);

var config bool bCompressMessages;
