/*******************************************************************************
* RegionConfig_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class RegionConfig_X extends OnlineConfig_X;

var array<SuperRegion_X> SuperRegions;
var array<Region_X> Regions;
