/*******************************************************************************
* SocialMetrics_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class SocialMetrics_X extends MetricsGroup_X;

defaultproperties
{
	Category="Social"
}