/*******************************************************************************
* BlogConfig_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class BlogConfig_X extends OnlineConfig_X;

var array<BlogTile_X> Entries;
var string MotD;
var float RetryTime;

defaultproperties
{
	RetryTime=15.0
}