/*******************************************************************************
* CDN_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class CDN_X extends Object
	config(Engine);

var config string URL;
var config string BlogURL;
