/*******************************************************************************
* CheatManager_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class CheatManager_X extends CheatManager within PlayerController_X;

struct TestStructEvent
{

	structdefaultproperties
	{
		
	}
};

