/*******************************************************************************
* CrossplayConfig_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class CrossplayConfig_X extends OnlineConfig_X;

var() array<CrossplayGroup> Groups;
var() array<CrossplayGroup> DisabledCrossplayGroups;
