/*******************************************************************************
* DecodeObject_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class DecodeObject_X extends Object
	abstract;

var int Checksum;
var Error Error;
