/*******************************************************************************
* EncodeObjectJson_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class EncodeObjectJson_X extends EncodeObject_X;

var JSONSerializer_X JsonSerializer;
