/*******************************************************************************
* FuncTestDesc_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class FuncTestDesc_X extends Object;

var string TestName;
var array<name> Tags;
var array<FuncTestGroup_X> Groups;
