/*******************************************************************************
* LoginResponse_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class LoginResponse_X extends Object;

var transient string BannedMessage;
var transient int BannedMinutes;
