/*******************************************************************************
* PartyPlatformSession_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class PartyPlatformSession_X extends Object within Parties_X;

var UniqueLobbyId PartyID;
