/*******************************************************************************
* PlatformSystem_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class PlatformSystem_X extends Object
	abstract;
