/*******************************************************************************
* Region_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class Region_X extends Object;

var string SuperRegionID;
var string Id;
var string Label;
var string Secret;
