/*******************************************************************************
* RetryDelay_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class RetryDelay_X extends Object;

var name Id;
var array<float> DelaySeconds;
var bool bUseRandomMultiplier;

defaultproperties
{
	bUseRandomMultiplier=true
}