/*******************************************************************************
* TimeWindowOptional_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class TimeWindowOptional_X extends Object;

var Qword StartTime;
var Qword EndTime;
var IEpochNow Time;
