/*******************************************************************************
* Timers_X generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class Timers_X extends Object;

var export editinline transient TickComponent_X TickComponent;
