/*******************************************************************************
* AchievementUnlockedEvent_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class AchievementUnlockedEvent_TA extends Object;

var _Types_TA.EAchievementType Type;
var int LocalId;
