/*******************************************************************************
* CameraTrackPoint_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class CameraTrackPoint_TA extends Object;

var int frame;
var float Time;
var Vector Location;
var Rotator Rotation;
var float FOV;
