/*******************************************************************************
* ChallengeFilter_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class ChallengeFilter_TA extends Object within ChallengeFolder_TA
	abstract;
