/*******************************************************************************
* ChampionshipTrophy_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class ChampionshipTrophy_TA extends Object;

var ScreenDisplayActor_TA ChampionshipTrophyArchetype;
var AkSoundCue ChampionshipTrophySound;
