/*******************************************************************************
* Eula_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class Eula_TA extends LegalText_TA;

var /*0x00008000-0x00000000*/ EulaConfig_TA EulaConfig;
