/*******************************************************************************
* InterpTrackInstVehicleToggle_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class InterpTrackInstVehicleToggle_TA extends InterpTrackInstToggle;

var transient Vehicle_TA TargetVehicle;
