/*******************************************************************************
* K3SUserPermissionsError_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class K3SUserPermissionsError_TA extends Object;

var string ErrorCode;
var string Message;
