/*******************************************************************************
* MatchAdminComponent_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class MatchAdminComponent_TA extends Object;

var /*0x00010000-0x00000000*/ GameEvent_TA GameEvent;
var /*0x00018000-0x00000000*/ OnlinePlayerPermissions_X PlayerPermissions;
