/*******************************************************************************
* MusicTracklist_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class MusicTracklist_TA extends Object
	implements(IMusicTracklist_TA);

var array<MusicTrack_TA> Tracks;
