/*******************************************************************************
* Mutator_Car_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class Mutator_Car_TA extends Mutator_TA;

var() float CarScale;
var() float JumpScale;
var() float CarMaxLinearSpeedScale;
