/*******************************************************************************
* Mutator_Loadout_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class Mutator_Loadout_TA extends Mutator_TA;

var() array<Product_TA> Products;
