/*******************************************************************************
* Note_Linked_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class Note_Linked_TA extends Note
	hidecategories(Navigation);

var() Note_Linked_TA NextNote;
var() Note_Linked_TA PrevNote;

defaultproperties
{
	DrawScale=0.50
}