/*******************************************************************************
* PriAssetCache_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class PriAssetCache_TA extends Object;

var PRI_TA PRI;
var array<int> Products;
