/*******************************************************************************
* StatusTriggerManager_TA generated by MVN.RLLib using AssetExtraction.
* MVN.RLLib © 2019 Martin VN. All rights reserved.
* All rights belong to their respective owners.
*******************************************************************************/
class StatusTriggerManager_TA extends Object;

var array<StatusObserver_X> Observers;
var array<TriggerCondition_TA> Conditions;
